# Site settings
title: 'FABIOHCNOBRE'
description: Developer
tagline: Fabio Nobre Developer | Site do Fabio Nobre, desenvolvedor de software
description: Site do Fabio Nobre, desenvolvedor de software
url: 'https://fabiohcnobre.dev.br/'
author: Fabio Nobre

# User settings
username: FabioHCNobre
user_description: Software Developer
user_title: Software Developer
email: fabiohcnobre@hotmail.com
whatsapp:  https://api.whatsapp.com/send/?phone=5535984151764 
twitter_username: fabiohcnobre
github_username:  fabiohcnobre 
linkedin_username:  fabiohcnobre 
chrome_mobile_color: 3942E4

# Google-analytics
google-analytics:
  id: G-LXPK0J0Z28

exclude: ['package.json', 'src' , 'node_modules']

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "UTF-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false
