# Site settings
title: 'FABIOHCNOBRE'
description: Developer
url: 'https://fabiohcnobre.github.io/'

# User settings
username: FabioHCNobre
user_description: Software Developer
user_title: Software Developer
email: fabiohcnobre@hotmail.com
twitter_username: fabiohcnobre
github_username:  fabiohcnobre 
linkedin_username:  fabiohcnobre 
chrome_mobile_color: 1976d2

# Google-analytics
google-analytics:
  id: G-LXPK0J0Z28

exclude: ['package.json', 'src' , 'node_modules']

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "UTF-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false
